twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        sitename: '%sitename%'
        project_links: '%project_links%'
        default_content_language: '%default_content_language%'
        analytics_snippet: '%analytics_snippet%'
        js_path: '%js_path%'
        script_library: '%script_library%'
        asset_version: '+version%asset_version%'
        global_info_message: '%global_info_message%'

when@test:
    twig:
        strict_variables: true
