<?php
$mainFgColor = '#000000';
$mainBgColor = '#F9F6E6';#F9F3D9 FCF9E9

$headerFgColor = $mainFgColor;
$headerBgColor = '#FFEB8F';
$headerBordColor = '#FFD100';
$headerShadowColor = $headerBgColor;

$linkFgColor = '#8F1700';
$alinkFgColor = '#AF0C00';
$vlinkFgColor = '#4F1C00';
// $linkFgColor = '#0000EE';
// $alinkFgColor = '#EE0000';
// $vlinkFgColor = '#551A8B';

$fieldsetBordColor = $headerBordColor;
$legendFgColor = '#D03030';

$formElemFgColor = $mainFgColor;
$formElemBgColor = $mainBgColor;
$formElemFocusBgColor = '#FFFFFF';

$submitButtonFgColor = $mainFgColor;
$submitButtonBgColor = '#FDED6D';

$logoFgColor = '#FFAA00';
$logoBgColor = $mainBgColor;

$toolbarFgColor = $mainFgColor;
$toolbarBgColor = '#FFF1AF';#'#FFF096';
$toolbarBordColor = '#FFDA2F';

$navFgColor = $mainFgColor;
$navBgColor = $mainBgColor;
$navTitleFgColor = '#FFFFFF';
$navTitleShadowColor = 'black';
$navTitleBgColor = $logoFgColor;
$navLinkFgColor = '#7F4500';

$tocFgColor = $mainFgColor;
$tocBgColor = '#FFFCEF';
$tocBordColor = $fieldsetBordColor;

$buttonLinksFgColor = '#CF5919';
$buttonLinksBgColor = $tocBgColor;

$footerFgColor = $toolbarFgColor;
$footerBgColor = $toolbarBgColor;
$footerBordColor = $toolbarBordColor;

$readMarkFgColor = $mainFgColor;
$readMarkBgColor = 'inherit';

$codeFgColor = '#003300';
$codeBgColor = '#FCFCFC';
$codeBordColor = '#C0C0C0';

$errorFgColor = '#CC0000';
$extraInfoFgColor = '#333333';
$extLinkFgColor = '#006F4E';
$insBgColor = '#DDFFDD';
$delBgColor = '#FFCCCC';

$oddFgColor = $mainFgColor;
$oddBgColor = $mainBgColor;
$evenFgColor = $mainFgColor;
$evenBgColor = $tocBgColor;#'#F0EDE3';

$cloudFgColor = '#2F2200';
$cloudBordColor = '#DFA200';
$cloudFgHoverColor = $cloudFgColor;
$cloudBgHoverColor = '#FFEB8F';
$cloudBg1Color = '#FFF6DF';/*#EFF9FF*/
$cloudBg2Color = '#FFEEBF';/*#DFF4FF*/
$cloudBg3Color = '#FFE59F';/*#CFEEFF*/
$cloudBg4Color = '#FFE08F';/*#BFE8FF*/
$cloudBg5Color = '#FFDC7F';/*#AFE3FF*/
$cloudBg6Color = '#FFD86F';/*#9FDDFF*/

$dashboardBorderColor = '#f7a250 #f7a050 #ef925e #f6a460';
$dashboardBgColor = '#FF953F';
$dashboardBg1Color = 'rgba(246, 132, 36, 0.8)';
$dashboardBg2Color = 'rgba(255, 157, 79, 0.9)';
$dashboardBoxShadowColor = 'rgba(237, 96, 46, 0.5)';
