#jms_security_extra:
#    secure_all_services: false
#    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: App\Entity\User, property: username }
        test:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false

#        backend:
#            pattern:    ^/admin/
#            form_login:
#                check_path: /admin/login_check
#                login_path: /admin/login
#            logout:
#                path:   /logout
#                target: /
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"
        public:
            pattern:     /.*
            form_login:  true
            anonymous:   true
            logout:      true
            switch_user: true
#         main:
#             form_login:
#                 provider: fos_userbundle
#                 provider: fos_userbundle

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        - { path: ^/_internal, roles: ROLE_NO_ACCESS }
#        - { path: /.*, role: IS_AUTHENTICATED_ANONYMOUSLY }


# fos_user.config:
#     db_driver: orm
#     provider_key: main
#     class:
#         model:
#             user: App\Entity\User
